/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface EncodedResult {
  shards: Array<Buffer>
  k: number
  n: number
  originalLength: number
  indices: Array<number>
}
export interface ValidationResult {
  isValid: boolean
  errors: Array<string>
  warnings: Array<string>
}
export declare class RustReedSolomon {
  constructor(k: number, n: number)
  encode(data: Buffer, shardSize: number): EncodedResult
  decode(shards: Array<Buffer>, originalLength: number): Buffer
  recover(shards: Array<Buffer>, corruptedIndices: Array<number>, originalLength: number): Buffer
  validate(k: number, n: number): ValidationResult
  getK(): number
  getN(): number
  getParityShards(): number
}
