/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface EncodedResult {
  shards: Buffer[]
  k: number
  n: number
  originalLength: number
  indices: number[]
}
export interface ValidationResult {
  isValid: boolean
  errors: string[]
  warnings: string[]
}
export declare class RustReedSolomon {
  constructor(k: number, n: number)
  encode(data: Buffer, shardSize: number): EncodedResult
  decode(shards: Buffer[], originalLength: number): Buffer
  recover(
    shards: Buffer[],
    corruptedIndices: number[],
    originalLength: number,
  ): Buffer
  validate(k: number, n: number): ValidationResult
  getK(): number
  getN(): number
  getParityShards(): number
}
