//! Codec module (mirrors assembly/codec.ts).
//! Gray Paper serialization: decodeBlob, encodeBlob, decodeProgramFromPreimage,
//! decodeAccumulateArgs, decodeVariableSequence, encodeVariableSequence,
//! decodeImplicationsPair, encodeImplicationsPair (stub).

#![allow(unused_imports)]

mod impl_;

pub use impl_::{
    create_preimage_key,
    create_storage_key,
    decode_accumulate_args,
    decode_blob,
    decode_complete_service_account,
    decode_deferred_transfer,
    decode_fixed_length,
    decode_implications,
    decode_implications_pair,
    decode_natural,
    decode_partial_state,
    decode_program,
    decode_program_from_preimage,
    decode_provision_entry,
    decode_request_timeslots,
    decode_service_code_from_preimage,
    decode_variable_length,
    decode_variable_sequence,
    delete_preimage_value,
    delete_request_value,
    delete_storage_value,
    DecodedAccumulateArgs,
    DecodedBlob,
    DecodedProgram,
    DecodingResult,
    encode_complete_service_account,
    encode_deferred_transfer,
    encode_implications,
    encode_implications_pair,
    encode_partial_state,
    encode_provision_entry,
    get_preimage_value,
    get_request_value,
    get_storage_value,
    set_request_value,
    encode_request_timeslots,
    Implications,
    ImplicationsPair,
    PartialState,
    AccountEntry,
    AlwaysAccerEntry,
    CompleteServiceAccount,
    DeferredTransfer,
    ProvisionEntry,
    ServiceCodeResult,
    set_storage_value,
    encode_blob,
    encode_fixed_length,
    encode_natural,
    encode_variable_sequence,
};
